spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/how
    username: tfg
    password: tfg
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  profiles:
    active: dev
    
name: dev
---
spring:
  profiles: prod
name: prod