spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/how
    username: tfg
    password: tfg
    driverClassName: org.postgresql.Driver
    continueOnError: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/how
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  profiles:
   active: local
    
name: local
---
spring:
  profiles: heroku
name: heroku